name: CheckScripts

# spell-checker:ignore ludeeus mfinelli

env:
  SCRIPT_DIR: 'util'

on:
  push:
    branches:
      - main
    paths:
      - 'util/**/*.sh'
  pull_request:
    branches:
      - main
    paths:
      - 'util/**/*.sh'

# End the current execution if there is a new changeset in the PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  shell_check:
    name: ShellScript/Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: warning

  shell_fmt:
    name: ShellScript/Format
    runs-on: ubuntu-latest
    needs: [ shell_check ]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup shfmt
        uses: mfinelli/setup-shfmt@v2
      - name: Run shfmt
        shell: bash
        run: |
          # show differs first for every files that need to be formatted
          # fmt options: bash syntax, 4 spaces indent, indent for switch-case
          find ${{ env.SCRIPT_DIR }} -name "*.sh" | xargs shfmt -ln=bash -i 4 -ci -d
          # do shell format
          find ${{ env.SCRIPT_DIR }} -name "*.sh" | xargs shfmt -ln=bash -i 4 -ci -w
      - name: Commit any changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "style: auto format (shfmt)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
